Initial commit

diff --git a/.github/workflows/push.yml b/.github/workflows/push.yml
--- a/.github/workflows/push.yml
+++ b/.github/workflows/push.yml
@@ -23,19 +23,8 @@ env:
 
   ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
   ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
-  ARM_ENVIRONMENT: ${{ secrets.ARM_ENVIRONMENT }}
-  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
   ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
-  AZOPS_MODULE_VERSION: ${{ secrets.AZOPS_MODULE_VERSION }}
-
-  #
-  # modulesFolder
-  # To enable caching of PowerShell modules between
-  # runs, the modules are stored in a modules folder
-  # that can be cached.
-  #
-  
-  modulesFolder: "~/.local/share/powershell/Modules"
+  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
 
 jobs:
 
@@ -61,21 +50,63 @@ jobs:
           fetch-depth: 0
 
       #
-      # Shared steps
-      # Include shared steps from the 'action.yml' file
-      # to not have to repeat them in every pipeline.
+      # Dependencies
+      # Install required runtime modules
       #
 
-      - name: 'Shared steps'
-        uses: ./.github/actions/sharedSteps
+      - name: "Dependencies"
+        shell: pwsh
+        run: |
+          Install-Module -Name "AzOps" -Force
+
+      #
+      # Connect
+      # Authenticate Azure context
+      #
+
+      - name: "Connect"
+        shell: pwsh
+        run: |
+          $credential = New-Object PSCredential -ArgumentList $env:ARM_CLIENT_ID, (ConvertTo-SecureString -String $env:ARM_CLIENT_SECRET -AsPlainText -Force)
+          Connect-AzAccount -TenantId $env:ARM_TENANT_ID -ServicePrincipal -Credential $credential -SubscriptionId $env:ARM_SUBSCRIPTION_ID
+
+      #
+      # Diff
+      # List index changes
+      #
+
+      - name: "Diff"
+        shell: bash
+        run: |
+          if [ ! -z "$(git diff --name-status HEAD^ HEAD)" ]; then
+            echo $(git diff --name-status HEAD^ HEAD)
+            git diff --name-status HEAD^ HEAD > /tmp/diff.txt
+            if [ ! -z "$(git diff --diff-filter=D HEAD^ HEAD)" ]; then
+              echo $(git diff --diff-filter=D HEAD^ HEAD  --no-prefix | grep ^- | sed -r "s/^([^-+ ]*)[-+ ]/\\1/" | less -r)
+              git diff --diff-filter=D HEAD^ HEAD --no-prefix | grep ^- | sed -r "s/^([^-+ ]*)[-+ ]/\\1/" | less -r > /tmp/diffdeletedfiles.txt
+            fi
+          else
+            echo "The validation pipeline failed because there is currently no change to be processed"
+            exit 1
+          fi
 
       #
       # Deploy
-      # Deploy any templates changed in the last commit
+      # Initial deployment of any index changes
       #
-     
-      - name: 'Deploy'
-        with:
-          deploy: true
-          name: 'Deploy'
-        uses: ./.github/actions/validate-deploy
+
+      - name: "Deploy"
+        shell: pwsh
+        run: |
+          Import-PSFConfig -Path settings.json -Schema MetaJson -EnableException
+          Initialize-AzOpsEnvironment
+          $diff = Get-Content -Path /tmp/diff.txt
+          $module = Get-Module -Name AzOps
+          if(Test-Path -Path "/tmp/diffdeletedfiles.txt") {
+            $diffdeletedfiles = Get-Content -Path /tmp/diffdeletedfiles.txt
+            $module.Invoke({ Invoke-AzOpsPush -ChangeSet $diff -DeleteSetContents $diffdeletedfiles })
+          }
+          else {
+            $module.Invoke({ Invoke-AzOpsPush -ChangeSet $diff })
+          }
+          Get-Job | Remove-Job -Force
